name: SYNC
env:
  # Username/email used to commit to Cloud Manager's Git repository
  USER_NAME: dunguyen-adobe-com
  USER_EMAIL: dunguyen@adobe.com
  # Directory within the Cloud Manager Git repository
  PROJECT_DIR: /
  # Cloud Manager's Git repository
  MAIN_REPOSITORY: git.cloudmanager.adobe.com/adobeio/AdobeIO-p22654-SPA/
  # The branch in Cloud Manager's Git repository to push to
  MAIN_BRANCH : master
 
# Only run on a push to this branch
on:
  push:
     branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Checkout this project into a sub folder
      - uses: actions/checkout@v2
        with:
          path: sub
      # Cleanup sub project
      - name: Clean project
        run: |
          git -C sub log --format="%an : %s" -n 1 > commit.txt
          rm -rf sub/.git
          rm -rf sub/.github
      # Set global git configuration
      - name: Set git config
        run: |
          git config --global credential.helper cache
          git config --global user.email ${USER_EMAIL}
          git config --global user.name ${USER_NAME}
      # Checkout the main project
      - name: Checkout main project
        env:
          USERNAME: ${{ secrets.MAIN_USER }}
          PASSWORD: ${{ secrets.MAIN_PASSWORD }}
        run:
          git clone -b ${MAIN_BRANCH} https://${USERNAME}:${PASSWORD}@${MAIN_REPOSITORY} main 
      # Move sub project
      - name: Move project to main project
        run: |
          rm -rf sub/.git/
          cp -rf main/.git sub/
      - name: Commit Changes
        run: |
          git -C sub add -f .
          git -C sub commit -F ../commit.txt
          git -C sub push